---
title: "Untitled"
output: html_document
date: "2024-12-09"
---

# p5-3
# step1: 导入数据

```{r}

## 样本基本信息
point0 <- "P5-4"
point <- "P5_4"
date0 <- "20250115"
label0 <- "KingMed"

##
options(scipen = 200)
path0 <- paste0("/Users/hanazh/300_ZJProgram1/305_KingMed/305_2_KingMed_cleandata/KingMed_", date0, "/")
setwd(path0)
getwd()

## test
library(readxl)
datapath <- paste0(date0, "_原始数据.xlsx")
data.test <- read_excel(datapath)
# data.test <- subset(data.test,  (data.test$样本编码 != "1") | (is.na(data.test$样本编码)))
names(data.test)
# data <- data.test
# data$检测项目 <- data$项目简称
# data$浓度值 <- data$结果
# data$检测时间 <- data$完成时间
# dput(names(data))
# data.test <- data

## demo
data.demo <- read_excel("上传模版.xlsx")

## id
data.id <- read_excel(paste0("表2_课题一送样清单_", point0, "_", date0, ".xlsx"))
names(data.id)
data.id <- data.id[, c("红盒ID-1")]
colnames(data.id) <- "id"
# data.id$id <- sub("S[123]$", "", data.id$id)
# data.id$id <- sub("S[123]?$", "", data.id$id)
data.id$id <- sub("[Ss][123]?$", "", data.id$id)

# Find duplicated IDs
duplicates <- data.id$id[duplicated(data.id$id)]  # "370321199710280020-1"
print(duplicates)

data.id <- data.id[!duplicated(data.id$id), ]

# names(data.test)
# test <- subset(data.test,  data.test$样本条码 == "370321199710280020-1S1")
library(magrittr)

```

# 数据结构核查

```{r}
data <- data.test
sum(is.na(data))

# 保存图形为 TIFF 格式
tiff(paste0("KingMed", date0, "_missing_data_overview.tiff"), width = 8, height = 6, units = "in", res = 300)
# 绘制缺失值图示
library(VIM)
aggr(data, numbers = TRUE, sortVars = TRUE, cex.axis = 0.7, gap = 3, 
     col = c("gray", "red"), ylab = c("缺失数据概览", "模式"))
dev.off()

## 测试单位
data$unit <- paste(data$检测项目, data$单位, sep = "_")
unite <- as.data.frame(table(data$unit))

```

# 核对离群值

```{r}
data <- data.test
names(data)

data <- data %>% 
  dplyr::select(
    c("样本条码", "检测项目", "浓度值")
  )

colnames(data) <- c("id", "index", "value")

data$value <- as.numeric(data$value)
library(ggplot2)

# 假设数据框 figure 包含以下列：ID, index, value
ggplot(data, aes(x = value, fill = index)) +
  geom_histogram(binwidth = function(x) (max(x, na.rm = TRUE) - min(x, na.rm = TRUE)) / 30, 
                 alpha = 0.6, position = "dodge") +
  facet_wrap(~ index, scales = "free") +
  theme_minimal() +
  labs(title = "Histogram of Multiple Indicators with Dynamic Binwidth",
       x = "Value", y = "Frequency")


library(ggplot2)
ggplot(data, aes(x = index, y = value, fill = index)) +
  geom_boxplot(alpha = 0.6, outlier.shape = NA) +  # 使用 geom_boxplot 绘制箱线图
  geom_jitter(width = 0.2, alpha = 0.4, size = 1, color = "black") +  # 添加散点表示数据分布
  theme_minimal() +
  labs(title = "Boxplot of Multiple Indicators",
       x = "Indicator", y = "Value") +
  theme(legend.position = "none")  # 隐藏图例（如果不需要）

library(ggplot2)
ggplot(data, aes(x = index, y = value, fill = index)) +
  geom_boxplot(alpha = 0.6, outlier.shape = NA) +  # 绘制箱线图
  geom_jitter(width = 0.2, alpha = 0.4, size = 1, color = "black") +  # 添加散点表示数据分布
  theme_minimal() +
  facet_wrap(~ index, scales = "free") +  # 根据 index 分面
  labs(title = "Faceted Boxplot of Multiple Indicators",
       x = "Indicator", y = "Value") +
  theme(legend.position = "none",           # 隐藏图例
        strip.text = element_text(size = 10),
        panel.background = element_rect(fill = "white", color = NA),  # 面板背景为白色
        plot.background = element_rect(fill = "white", color = NA)    # 整体背景为白色
        )  # 调整分面标题字体大小

# 保存为 TIFF 文件
ggsave(paste0("KingMed_", date0, "_", "Boxplot.tiff"), width = 12, height = 8, units = "in", dpi = 300)


library(ggplot2)
library(dplyr)
# 动态计算 binwidth
binwidths <- data %>%
  group_by(index) %>%
  summarise(binwidth = (max(value, na.rm = TRUE) - min(value, na.rm = TRUE)) / 30) # 30 个区间

# 将 binwidth 加入到原数据框
figure <- data %>%
  left_join(binwidths, by = "index")

# 绘制图形
p <- ggplot(data, aes(x = value, fill = index)) +
  geom_histogram(binwidth = function(x) (max(x, na.rm = TRUE) - min(x, na.rm = TRUE)) / 30, alpha = 0.6) +
  facet_wrap(~ index, scales = "free") +
  theme_minimal() +
  labs(title = "Histogram of Multiple Indicators with Dynamic Binwidth",
       x = "Value", y = "Frequency") +
  theme(panel.background = element_rect(fill = "white", color = NA),  # 面板背景为白色
        plot.background = element_rect(fill = "white", color = NA)    # 整体背景为白色
        )

# 保存为 TIFF 文件
ggsave(paste0("KingMed_", date0, "_", "dynamic_histograms.tiff"), plot = p, width = 12, height = 8, units = "in", dpi = 300)


```


# step4: cleandata
## 15_index

```{r}

data <- data.test
names(data)

## main varibles
data <- data %>% 
  dplyr::select(
    c("样本条码", "检测时间", "检测项目", "浓度值")
  )
colnames(data) <- c("id", "time", "index", "value")
# data$id <- sub("S[123]$", "", data$id)
# data$id <- sub("S[123]?$", "", data$id)
data$id <- sub("[CSs][123]?$", "", data$id)
# 将小写 x 替换为大写 X
data$id <- gsub("x", "X", data$id)

## time style
# data$time <- as.POSIXct(data$time, format = "%Y/%m/%d %H:%M:%S")
data$time <- gsub("/", "-", data$time)

## 12_index
library(tidyr)
data <- data %>% # 按样本条码分组，并选择每组的第一个检测时间 
  group_by(id) %>% 
  mutate(time = min(time)) %>% 
  ungroup() %>% # 转换为宽格式 
  pivot_wider(names_from = index, values_from = value )

dput(names(data))
data <- data %>% 
  dplyr::select(
    c("id", "time", 
      "FSH", "LH", "E2", "PROG", "PRL", 
      "TESTO", "AMH", "DHEA-S", "SHBG", "ASD", 
      "17α-OHP", "INHB",
      "Anti-TPO", "FT3", "TSH"
      )
  )


# Find duplicated IDs
duplicates <- data$id[duplicated(data$id)]
print(duplicates)
data.a <- data



##
new_df <- paste(label0, point, date0, sep = "_")
assign(new_df, data)

## save 12 index
save(list = new_df,
     file = paste0(new_df, ".RData")
     )
load(paste0(path0, new_df, ".RData"))

```

## LOD


```{r}
## data
data <- data.a
dput(names(data))
# 定义需要统计的检测变量
vars <- c("FSH", "LH", "E2", "PROG", "PRL", "TESTO", "AMH", "DHEA-S", "SHBG", "ASD", "17α-OHP", "INHB", "Anti-TPO", "FT3", "TSH")

# 统计检出率
result <- sapply(vars, function(var) {
  # 总样本数
  total <- nrow(data)
  # 非检出限值的数量（不以 "<" 开头）
  detected <- sum(!startsWith(data[[var]], "<"))
  # 计算检出率
  detected / total
})

# 转换为数据框显示结果
result_df <- data.frame(
  Variable = vars,
  DetectionRate = result
)

# 打印结果
print(result_df)


result_df <- data.frame(
  Variable = vars,
  DetectionRate = sapply(vars, function(var) sum(!startsWith(data[[var]], "<")) / nrow(data)),
  BelowLimit = sapply(vars, function(var) sum(startsWith(data[[var]], "<"))),
  Total = nrow(data),
  test_time = date0
)
# 按检出率升序排序
result_df <- result_df[order(result_df$DetectionRate), ]

print(result_df)

## demo
data.index <- read_excel("test.xlsx")
data.index <- data.index[, 1]
data.index$Variable <- data.index$v

data <- left_join(data.index, result_df, by = "Variable")

## save excel
library(writexl)
write_xlsx(data, path = "result_LOD.xlsx")


```



## 10_index_uoload

```{r}
## data
data <- data.a
names(data)
data <- data %>% 
  dplyr::select(
    c("id", "time", 
      "FSH", "LH", "E2", "PROG", "PRL", 
      "TESTO", "AMH", "DHEA-S", "SHBG", "ASD")
  )

## id

data <- left_join(data.id, data, by = "id")

## delete missing data
data <- data %>% 
  dplyr::filter(
    !is.na(time)
  )

names(data)
names(data.demo)
names(data) <- names(data.demo)

## save excel
library(writexl)
write_xlsx(data, path = paste0(label0, "_", point, "_", date0, "_","Upload", ".xlsx"))


```

# step5: Double Check


```{r}
## zhangzhi
data1 <- read_excel(paste0(date0, "_上传数据+时间.xlsx"))
# data1 <- data1[-c(1), ]
# data1$`检测时间[testTime]` <- gsub("/", "-", data1$`检测时间[testTime]`)
# names(data1)

##
data1$`条形码（身份证号-1或-2）[barcode]` <- gsub("x", "X", data1$`条形码（身份证号-1或-2）[barcode]`)

## hanazh
data2 <- read_excel(paste0(label0, "_", point, "_", date0, "_","Upload", ".xlsx"))
# names(data2)

##
diff_vars <- setdiff(names(data1), names(data2)) 
print(diff_vars)

##  names diff
names(data1) <- names(data2)

# 比较两个数据框是否完全一致(忽略顺序)
setequal(data1, data2)    ## TRUE 表示可以上传数据框

# all.equal(data1, data2)  # 提供具体的差异信息
# 找出 data1 和 data2 的列名差异
setdiff(names(data1), names(data2)) # data1 中有但 data2 没有的列
setdiff(names(data2), names(data1)) # data2 中有但 data1 没有的列
# 找出 data1 中有但 data2 中没有的行
diff_data1 <- dplyr::anti_join(data1, data2)
diff_data2 <- dplyr::anti_join(data2, data1)

# 比较两数据框并找出差异
difference <- data1 != data2

# 哪些行列不一致
which(difference, arr.ind = TRUE)

```


## 10_index_uoload_97

```{r}
## data
data <- data.a
names(data)
data <- data %>% 
  dplyr::select(
    c("id", "time", 
      "FSH", "LH", "E2", "PROG", "PRL", 
      "TESTO", "AMH", "DHEA-S", "SHBG", "ASD")
  )

## id

data <- left_join(data.id, data, by = "id")

## delete missing data
data <- data %>% 
  dplyr::filter(
    !is.na(time)
  )

names(data)
names(data.demo)
names(data) <- names(data.demo)

# 删除-月经期修改为非月经期
data <- data %>% 
  dplyr::filter(
    ! `条形码（身份证号-1或-2）[barcode]` %in% c("130826198705273221-2", "130823199805155025-2")
  )

## save excel
library(writexl)
write_xlsx(data, path = paste0(label0, "_", point, "_", date0, "_","Upload_97", ".xlsx"))

```


## 10_index_uoload_2

```{r}
## data
data <- data.a
names(data)
data <- data %>% 
  dplyr::select(
    c("id", "time", 
      "FSH", "LH", "E2", "PROG", "PRL", 
      "TESTO", "AMH", "DHEA-S", "SHBG", "ASD")
  )

## id

data <- left_join(data.id, data, by = "id")

## delete missing data
data <- data %>% 
  dplyr::filter(
    !is.na(time)
  )

names(data)
names(data.demo)
names(data) <- names(data.demo)

# 删除-月经期修改为非月经期
data <- data %>% 
  dplyr::filter(
     `条形码（身份证号-1或-2）[barcode]` %in% c("130826198705273221-2", "130823199805155025-2")
  )

# 使用 gsub 函数替换末尾的 -2 为 -1
data$`条形码（身份证号-1或-2）[barcode]` <- gsub("-2$", "-1", data$`条形码（身份证号-1或-2）[barcode]`)
## save excel
library(writexl)
write_xlsx(data, path = paste0(label0, "_", point, "_", date0, "_","Upload_2", ".xlsx"))

```